### ISSUE TITLE
Add support for Graphite web exp function

### ISSUE THREAD

**Issue by carrieedwards** [grafana/carbonapi#1]
**Is your feature request related to a problem? Please describe.**
The exp() function is implemented in Graphite web, but is missing from CarbonAPI.  In order to enable users to be able to use the exp() function, it needs to be implemented in CarbonAPI.

**Describe the solution you'd like**
The exp() function should be implemented in CarbonAPI, with the same functionality as the Graphite web function. The description of the function is as follows:

```
exp(seriesList)

Raise e to the power of the datapoint, where e = 2.718281… is the base of natural logarithms.
Example:
&target=exp(Server.instance01.threads.busy)

```

**Additional context**
Tests should be added to verify that the functionality matches that of the Graphite web exp() function.

**Comment by npazosmendez** [comment]
Closing this since https://github.com/grafana/carbonapi/pull/2 was merged
