### ISSUE TITLE
Add support for Graphite web logit function

### ISSUE THREAD

**Issue by carrieedwards** [grafana/carbonapi#13]
**Is your feature request related to a problem? Please describe.**
The logit() function is implemented in Graphite web, but is missing from CarbonAPI.  In order to enable users to be able to use the logit() function, it needs to be implemented in CarbonAPI.

**Describe the solution you'd like**
The logit() function should be implemented in CarbonAPI, with the same functionality as the Graphite web function. The description of the function is as follows:

```
logit(seriesList)
Takes one metric or a wildcard seriesList and applies the logit function log(x / (1 - x)) to each datapoint.

Example:

&target=logit(Server.instance01.threads.busy)
&target=logit(Server.instance*.threads.busy)

```

**Additional context**
Tests should be added to verify that the functionality matches that of the Graphite web logit() function.

**Comment by npazosmendez** [comment]
Closing this since https://github.com/grafana/carbonapi/pull/14 was merged
