### ISSUE TITLE
Add support for Graphite web sinFunction

### ISSUE THREAD

**Issue by carrieedwards** [grafana/carbonapi#38]
**Is your feature request related to a problem? Please describe.**
The sinFunction() function is implemented in Graphite web, but is missing from CarbonAPI.  In order to enable users to be able to use the sinFunction() function, it needs to be implemented in CarbonAPI.

**Describe the solution you'd like**
The sinFunction() function should be implemented in CarbonAPI, with the same functionality as the Graphite web function. The description of the function is as follows:

```
sinFunction(name, amplitude=1, step=60)
Short Alias: sin()

Just returns the sine of the current time. The optional amplitude parameter changes the amplitude of the wave.

Example:

&target=sin("The.time.series", 2)
This would create a series named “The.time.series” that contains sin(x)*2. Accepts optional second argument as ‘amplitude’ parameter (default amplitude is 1) Accepts optional third argument as ‘step’ parameter (default step is 60 sec)
```

**Additional context**
Tests should be added to verify that the functionality matches that of the Graphite web sinFunction() function.

**Comment by npazosmendez** [comment]
Closing this since https://github.com/grafana/carbonapi/pull/39 was merged
