### ISSUE TITLE
[BUG] legendValue panics on invalid "value types"

### ISSUE THREAD

**Issue by npazosmendez** [grafana/carbonapi#64]
This is legendValue's definition:
```
 legendValue(seriesList, *valueTypes)
```

This test for legendValue panics:

```
		{
			"legendValue(metric1,\"foo\")",
			map[parser.MetricRequest][]*types.MetricData{
				{"metric1", 0, 1}: {types.MakeMetricData("metric1", []float64{1, 2, 3, 4, 5}, 1, now32)},
			},
			[]*types.MetricData{types.MakeMetricData("metric1 (avg: 3)",
				[]float64{1, 2, 3, 4, 5}, 1, now32).SetNameTag("metric1")},
		},
```

because `foo` is not any of `last, avg, total, min, max`. It should return a nice error instead of panicking.

**Comment by npazosmendez** [comment]
@carrieedwards was this fixed? I can't find any PR that addressed this

**Comment by carrieedwards** [comment]
Ah, my apologies, I thought this was referring to a different issue that had been fixed. I'll re-open

**Comment by npazosmendez** [comment]
This was fixed here https://github.com/grafana/carbonapi/pull/102
