### ISSUE TITLE
[Discussion] Upstream?

### ISSUE THREAD

**Issue by Civil** [grafana/carbonapi#71]
Just wanted to open an issue as I've been asked, to track discussions about overall life with upstream.

By that I mean that we definitely should discuss how we pick features from each other, maybe have a discussion about overall directions of the project (I don't actively maintain things myself, however that doesn't mean that I don't plan to implement anything, and there are some active contributors as well).

And I think if we do that early enough we might save ourself from a lot of TOIL in the future.

**Comment by Civil** [comment]
Sure. My timezone is CEST and usually my evenings are free (or flexible) with exception of Wednesday. Weekends work as well, but I guess you won't work to discuss work-related stuff outside of working hours.

If you can't do evenings, I can try during my day, but that's likely would be Fridays and Mondays. Though I'll need to have a look at a calendar.

**Comment by carrieedwards** [comment]
Hi @Civil, would Wednesday, August 31st at 6:00 pm CEST work for you?

**Comment by Civil** [comment]
Unfortunately Wednesday is the only day a week that I can't do any meetings in the evening. In general 6 PM CEST works for me any other day.

**Comment by carrieedwards** [comment]
Would Thursday, September 1st at 6 pm CEST work for you?

**Comment by Civil** [comment]
Yup, that would work for me.

**Comment by carrieedwards** [comment]
Awesome. What is your email address, so I can send you a Zoom invite?

**Comment by Civil** [comment]
civil.over@gmail.com

**Comment by carrieedwards** [comment]
Great, I sent you the Zoom link

**Comment by Civil** [comment]
Thanks, got an email with invitation. So see you this Thursday (1st Sep, 6 PM CEST)!

**Comment by npazosmendez** [comment]
Closing this. We have already [sent our changes](https://github.com/go-graphite/carbonapi/pull/686) to the upstream :tada: and we plan we remain updated by sending regular PRs  and/or working directly on the upstream whenever we can.
