### ISSUE TITLE
Add support for Graphite web unique function

### ISSUE THREAD

**Issue by carrieedwards** [grafana/carbonapi#9]
**Is your feature request related to a problem? Please describe.**
The unique() function is implemented in Graphite web, but is missing from CarbonAPI.  In order to enable users to be able to use the unique() function, it needs to be implemented in CarbonAPI.

**Describe the solution you'd like**
The sigmoid() function should be implemented in CarbonAPI, with the same functionality as the Graphite web function. The description of the function is as follows:

```
unique(*seriesLists)
Takes an arbitrary number of seriesLists and returns unique series, filtered by name.

Example:

&target=unique(mostDeviant(server.*.disk_free,5),lowestCurrent(server.*.disk_free,5))
Draws servers with low disk space, and servers with highly deviant disk space, but never the same series twice.

```

**Additional context**
Tests should be added to verify that the functionality matches that of the Graphite web unique() function.

**Comment by npazosmendez** [comment]
Closing this since https://github.com/grafana/carbonapi/pull/10 was merged
